---
title: "What Happened?"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Here we can do an interactive graphic
this isn't too bad, probably took me an hour to pull this together
##here is a smaller header before the graph

```{r Display_KNN, echo=FALSE}
source('scripts/KNN.R')
   
   # Application title
   titlePanel("K Nearest Neighbors")
   
   # Sidebar with a slider input for number of bins 
   inputPanel(
     selectInput("features",
                     "Select Features",
                      choices = c('naturalized', 'non_citizen', 'female', 'foodstamp',
                  'age', 'white', 'black', 'asian_pac_islander', 'multi_racial',
                  'indig', 'hispanic', 'married', 'single', 'foreign_born',
                  'student', 'veteran', 'moved_last_year', 'col_degree',
                  'less_than_hs', 'grad', 'indig_land', 'farm',
                  'med_hhinc', 'med_age', 'med_hh_val'),
                     selected = 'med_age', multiple = TRUE),
     sliderInput('K',"Number of Neighbors",
                 min = 5, max = 100, value = 20, step = 1)
      )
    

renderPlot(
    display_KNN(input$K,input$features,1003), width = "auto", height = 850
   )


```


